[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
opti_freight = "AoR4goYR4q6mR1X6gB51CX67EbgzGmSYd6eWPN4A4ddq"
primary_market = "Az1M72qgA5REQjiV789DrSqgMG1UGrL7puRXEqBCAHFQ"
asset_nft = "2ESjYkkwqZYBkAA6gBprX9xaRhqgPVyMyZLkGVAq7YtU"
# secondary_market = "SECNdNgfnX8e4Qb1XAJ7H5YphWE87XKmWrk3nkzD8Vz"
# returns_distribution = "DVfDdWLdsin4LGgor4B1nNQTSe4oi5F4cfmRVafpeMog"
# governance = "GOVERNcaWJxH5YM3p8k6mwUhY7LzASwYxNzmgXzD4z"

[programs.localnet]
opti_freight = "AoR4goYR4q6mR1X6gB51CX67EbgzGmSYd6eWPN4A4ddq"
primary_market = "Az1M72qgA5REQjiV789DrSqgMG1UGrL7puRXEqBCAHFQ"
# asset_nft = "2ESdz2tgd6m8VPEcBnBPsndboKgMSDMQRUn94xD8YpUW"
# secondary_market = "SECNdNgfnX8e4Qb1XAJ7H5YphWE87XKmWrk3nkzD8Vz"
# returns_distribution = "DVfDdWLdsin4LGgor4B1nNQTSe4oi5F4cfmRVafpeMog"
# governance = "GOVERNcaWJxH5YM3p8k6mwUhY7LzASwYxNzmgXzD4z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/root/.config/solana/devnet-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[[test.genesis]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
program = "spl_token-3.5.0.so"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
